# SurvivalPlus Configuration

# A list of command aliases for the base command.
# The main command is /survivalplus
# Default: [sp]
command-aliases:
  - sp

modules:
  # Enable or disable the join/quit message module.
  # This module will suppress the join and quit messages when enabled.
  join-quit-message:
    enabled: true
  vein-miner:
    enabled: true
    # The maximum number of blocks that can be mined at once.
    max-blocks: 64
    # The list of blocks that can be vein-mined.
    mineable-ores:
      - "COAL_ORE"
      - "DEEPSLATE_COAL_ORE"
      - "COPPER_ORE"
      - "DEEPSLATE_COPPER_ORE"
      - "IRON_ORE"
      - "DEEPSLATE_IRON_ORE"
      - "GOLD_ORE"
      - "DEEPSLATE_GOLD_ORE"
      - "LAPIS_ORE"
      - "DEEPSLATE_LAPIS_ORE"
      - "REDSTONE_ORE"
      - "DEEPSLATE_REDSTONE_ORE"
      - "DIAMOND_ORE"
      - "DEEPSLATE_DIAMOND_ORE"
      - "EMERALD_ORE"
      - "DEEPSLATE_EMERALD_ORE"
      - "NETHER_GOLD_ORE"
      - "NETHER_QUARTZ_ORE"
  tool-storage:
    enabled: true
  ultimine:
    enabled: true
    # The maximum number of blocks that can be broken at once by the ultimine module.
    max-blocks: 64
  timber:
    enabled: true
    # The maximum number of logs that can be chopped at once.
    max-logs: 512
    # The radius to search for leaves around logs.
    leaf-search-radius: 10
    # The list of blocks considered logs.
    log-types:
      - "ACACIA_LOG"
      - "BIRCH_LOG"
      - "DARK_OAK_LOG"
      - "JUNGLE_LOG"
      - "OAK_LOG"
      - "SPRUCE_LOG"
      - "MANGROVE_LOG"
      - "CHERRY_LOG"
      - "STRIPPED_ACACIA_LOG"
      - "STRIPPED_BIRCH_LOG"
      - "STRIPPED_DARK_OAK_LOG"
      - "STRIPPED_JUNGLE_LOG"
      - "STRIPPED_OAK_LOG"
      - "STRIPPED_SPRUCE_LOG"
      - "STRIPPED_MANGROVE_LOG"
      - "STRIPPED_CHERRY_LOG"
      - "CRIMSON_STEM"
      - "WARPED_STEM"
      - "STRIPPED_CRIMSON_STEM"
      - "STRIPPED_WARPED_STEM"
    # The list of blocks considered leaves.
    leaf-types:
      - "ACACIA_LEAVES"
      - "BIRCH_LEAVES"
      - "DARK_OAK_LEAVES"
      - "JUNGLE_LEAVES"
      - "OAK_LEAVES"
      - "SPRUCE_LEAVES"
      - "MANGROVE_LEAVES"
      - "CHERRY_LEAVES"
      - "AZALEA_LEAVES"
      - "FLOWERING_AZALEA_LEAVES"
      - "NETHER_WART_BLOCK"
      - "WARPED_WART_BLOCK"
      - "SHROOMLIGHT"
  anticooldown:
    enabled: true
