# SurvivalPlus Configuration

# A list of command aliases for the base command.
# The main command is /survivalplus
# Default: [sp]
command-aliases:
  - sp

# Enable or disable modules here.
# To configure a specific module, edit its file in the 'configs' directory.
modules:
  join-quit-message:
    enabled: true
  vein-miner:
    enabled: true
  tool-storage:
    enabled: true
  ultimine:
    enabled: true
  timber:
    enabled: true
  anticooldown:
    enabled: true
  treasures:
    enabled: true
