# VeinMiner Module Settings

# The maximum number of blocks that can be mined at once.
max-blocks: 64

# The list of blocks that can be vein-mined.
mineable-ores:
  - "COAL_ORE"
  - "DEEPSLATE_COAL_ORE"
  - "COPPER_ORE"
  - "DEEPSLATE_COPPER_ORE"
  - "IRON_ORE"
  - "DEEPSLATE_IRON_ORE"
  - "GOLD_ORE"
  - "DEEPSLATE_GOLD_ORE"
  - "LAPIS_ORE"
  - "DEEPSLATE_LAPIS_ORE"
  - "REDSTONE_ORE"
  - "DEEPSLATE_REDSTONE_ORE"
  - "DIAMOND_ORE"
  - "DEEPSLATE_DIAMOND_ORE"
  - "EMERALD_ORE"
  - "DEEPSLATE_EMERALD_ORE"
  - "NETHER_GOLD_ORE"
  - "NETHER_QUARTZ_ORE"
